language: node_js
sudo: false
node_js:
- '4.4.7'
script: 
- npm test
- cd ../integration
- node .
cache:
  bundler: true
  directories:
  - node_modules
install: 
- npm install
- npm link .
- npm link sealious
- cd ../
- git clone https://github.com/sealcode/sealious-integration-tests.git
- cd sealious-integration-test
- npm install
- npm link sealious
after_success:
- npm run coveralls
after_deploy:
- npm dist-tag add sealious@`npm view sealious version` next
deploy:
  provider: npm
  email: kontakt@jakub-orlik.pl
  api_key:
    secure: jRcAYLwKjkAlM7Im2vZsYiGS/4EAaVhs9XD3toL4Hlt+9CopRhydyKJtOBxgylfe+XBEhFzjRhfqZNjIS5dgm9f9YeCAkmuPNlrYDDYRwRoGEFvvtUVHy06tn6mRv1N7prdH9cblicwY94iu0C7Rbv3XUGQPi506cdj5H4qjR9k=
  on:
    tags: true
    repo: Sealious/sealious
    branch: next
