language: node_js
node_js:
  - "0.12"
services:
  - mongodb
script: npm install && npm test
before_script: echo "before"
after_success:
- node ./lib/tests/prepare-test.js
- npm run prepare-coverage
- node ./node_modules/.bin/mocha tests/test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js 
- node ./lib/tests/undo-prepare-test.js