language: node_js
sudo: false
services:
- mongodb
node_js:
- '4.4.7'
script:
- npm test
- cd ../integration-tests
- npm run integration-tests
- cd ../sealious
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
- echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
- apt-get update
- apt-get install -y mongodb-org=3.2.9 mongodb-org-server=3.2.9 mongodb-org-shell=3.2.9 mongodb-org-mongos=3.2.9 mongodb-org-tools=3.2.9
install:
- npm install
- npm link .
- npm link sealious
- cd ../
- git clone https://github.com/sealcode/sealious-integration-tests.git integration-tests
- cd integration-tests
- git checkout alpha
- npm install .
- npm link sealious
- cd ../sealious
after_success:
- npm run coveralls
after_deploy:
- npm dist-tag add sealious@`npm view sealious version` next
deploy:
  provider: npm
  email: kontakt@jakub-orlik.pl
  api_key:
    secure: jRcAYLwKjkAlM7Im2vZsYiGS/4EAaVhs9XD3toL4Hlt+9CopRhydyKJtOBxgylfe+XBEhFzjRhfqZNjIS5dgm9f9YeCAkmuPNlrYDDYRwRoGEFvvtUVHy06tn6mRv1N7prdH9cblicwY94iu0C7Rbv3XUGQPi506cdj5H4qjR9k=
  on:
    tags: true
    repo: Sealious/sealious
    branch: next
