version: "3.2"
services:
  db:
    image: mongo:4.4-bionic
    ports:
      - "127.0.0.1:20722:27017"
  test:
    image: sealious-test:latest
    build:
      context: .
      dockerfile: test.dockerfile
    volumes:
      - ./:/opt/sealious/
      - sealious-nm:/opt/sealious/node_modules/
    links:
      - db
      - mailcatcher
    environment:
      - SEALIOUS_SMTP_HOST=mailcatcher
      - SEALIOUS_DB_HOST=db
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:1025:1025"
volumes:
  sealious-nm:
