version: '3.2'
services:
  db:
    image: mongo:3.4-jessie
    volumes:
      - type: volume
        source: mongo_db
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo_configdb
        target: /data/configdb
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:20722:27017"
  app:
    image: sealious-test-app-app:latest
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - type: bind
        source: ../
        target: /opt/sealious/
    ports:
      - "127.0.0.1:8083:8083"
    user: ${UID:-1000}:${GID:-1000}
  webserver:
    image: sealious-test-app-webserver:latest
    build:
      context: .
      dockerfile: webserver.dockerfile
    ports:
      - "127.0.0.1:83:83"
      - "127.0.0.1:446:446"
volumes:
  mongo_db:
  mongo_configdb:
